<style type="text/css">

.col3-layout .col-wrapper{
  float: left;
  width: inherit;
}


.col3-layout .col-wrapper .col-main {
    float: right;
    width: inherit;
}
.container{
/*  display: flex;*/
/*  padding: 1em;*/
/*  border: 1px solid gray;*/
  position: relative;
  box-shadow: 0px 0px 10px;
  justify-content: center;
}
.card {
  height: 300px;
}

pre{
  position: absolute;
  font-size: 20px;
  color: white;
  font-weight: 10px;
  left: 0;
  margin-left: 1em;
  bottom: 0;
  width: 50%;
}


.banner-heading{
  font-weight: bold;
  color: black;
}

</style>

<?php foreach ($this->getBrand() as $brand_id => $brand): ?>
<div class="container" style="width: 100%;">
    <div>
      <img src="<?php echo $this->getBaseUrl() . 'media' . DS . 'Brand' . DS . 'Banner' . DS . $brand->banner; ?>" width="100%">
      <pre>
        <h1 class="banner-heading"><?php echo $brand->name ?> </h1>
        <p><?php echo $brand->description ?></p>    
      </pre>
    </div>
    <?php endforeach ?>
</div>

<style type="text/css">
.banner-image{
  height: 500px;
  width: 100%;
  margin-left: -300px;
  position: relative;
  filter: drop-shadow(8px 8px 10px gray);
  filter: blur(1px);
}

.banner-text{
  width: 100%;
  height: 25%;
  position: absolute;
  top: 209px;
  color: gray;
  left: 36px;
}

.card-image {
    height: 175px;
    width: 100%;
    margin: auto;
    margin-bottom: 10px;
}

.product-div {
    display: inline-flex;
    margin-top: 1em;
    flex-wrap: wrap;
    justify-content: start-first;
}

.card{
/*  border: 1px solid gray;*/
/*  box-shadow: 5px 5px 4px;*/
  border-radius: 10px;
  margin-left: 2em;
  margin-bottom: 2em;
}

.category-div{
  display: block;
  width: 30em;
  margin-right: 1em;
  padding: 1em;
/*  border: 1px solid black;*/
}

.middle{
  display: flex;
}

</style>


<div class="middle">
  <div class="category-div">

  </div>
  <div class="product-div" >
    <?php foreach ($this->getProducts() as $product): ?>
      <div class="card m-1" style="width: 17rem; padding: 1em;">
        <img class="card-img-top card-image" src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($product->getImage()) ?>" alt="">
        <div class="card-body">
          <h5 class="card-title"><?php echo $product->name ?></h5>
          <p><?php echo $product->getShortDescription() ?></p>
          <p><b>$ <?php echo number_format($product->getPrice(), 2, '.', ',') ?></b></p>
          <?php echo $product->getUrlKey(); ?>
        </div>
    </div>
    <?php endforeach ?>
  </div> 
</div>