<style>
    .card {
        border-radius: 5px;
        padding: 20px;
        margin: 10px;
        width: 300px;
    }
    .card img {
    max-width: 100%;
    height: auto;
    border-radius: 5px;
    transition: transform 0.3s ease;
    }   

    .card:hover img {
        transform: scale(1.1);
    }

    .card img {
        max-width: 100%;
        height: auto;
    }

    .card h3 {
        font-size: 18px;
        margin-top: 10px;
    }

    .card h3:hover{
        text-decoration: none;
    }

    .card p {
        margin-top: 10px;
    }

    .heading{
        font-size: 25px;
        margin: 10px;
        text-align: center;
    }
    
    .card:hover img{
        transform: scale(1.1);
    }
</style>
<div class="heading">
    Featured 
    <span class="sub-heading">Brands</span>
</div>
<div style="display:flex; margin-bottom: 3rem;">
    <?php foreach ($this->getBrands() as $brand): ?>
        <div class="card">
              <img src="<?php echo Mage::getBaseUrl('media') . 'Brand' . DS . $brand->image; ?>" alt="<?php echo $brand->name; ?>" style="width:100%"/>
            </a></p>
            <center><h1><a href="<?php echo $this->getBaseUrl() . $brand->url_key; ?>"><?php echo $brand->name; ?></h1></a></center>
        </div>
    <?php endforeach; ?>
    </div>
</div>